2025-09-17 09:09:21.0545|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=An attempt was made to use the context instance while it is being configured. A DbContext instance cannot be used inside 'OnConfiguring' since it is still being configured at this point. This can happen if a second operation is started on this context instance before a previous operation completed. Any instance members are not guaranteed to be thread safe.|ExceptionStack=   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at UrlShortener.Data.Repositories.Implementation.RepositoryBase`1.FindByConditon(Expression`1 expression, Boolean AsNoTracking) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\RepositoryBase.cs:line 17
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:09:21.2711|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.|ExceptionStack=   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:09:41.1103|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=An attempt was made to use the context instance while it is being configured. A DbContext instance cannot be used inside 'OnConfiguring' since it is still being configured at this point. This can happen if a second operation is started on this context instance before a previous operation completed. Any instance members are not guaranteed to be thread safe.|ExceptionStack=   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at UrlShortener.Data.Repositories.Implementation.RepositoryBase`1.FindByConditon(Expression`1 expression, Boolean AsNoTracking) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\RepositoryBase.cs:line 17
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:09:41.3268|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.|ExceptionStack=   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:09:52.3132|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=An attempt was made to use the context instance while it is being configured. A DbContext instance cannot be used inside 'OnConfiguring' since it is still being configured at this point. This can happen if a second operation is started on this context instance before a previous operation completed. Any instance members are not guaranteed to be thread safe.|ExceptionStack=   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at UrlShortener.Data.Repositories.Implementation.RepositoryBase`1.FindByConditon(Expression`1 expression, Boolean AsNoTracking) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\RepositoryBase.cs:line 17
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:11:40.3825|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=An attempt was made to use the context instance while it is being configured. A DbContext instance cannot be used inside 'OnConfiguring' since it is still being configured at this point. This can happen if a second operation is started on this context instance before a previous operation completed. Any instance members are not guaranteed to be thread safe.|ExceptionStack=   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at UrlShortener.Data.Repositories.Implementation.RepositoryBase`1.FindByConditon(Expression`1 expression, Boolean AsNoTracking) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\RepositoryBase.cs:line 17
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:12:59.1577|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.|ExceptionStack=   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:18:50.6959|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=An attempt was made to use the context instance while it is being configured. A DbContext instance cannot be used inside 'OnConfiguring' since it is still being configured at this point. This can happen if a second operation is started on this context instance before a previous operation completed. Any instance members are not guaranteed to be thread safe.|ExceptionStack=   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at UrlShortener.Data.Repositories.Implementation.RepositoryBase`1.FindByConditon(Expression`1 expression, Boolean AsNoTracking) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\RepositoryBase.cs:line 17
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:18:50.9145|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.|ExceptionStack=   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:18:52.7350|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=An attempt was made to use the context instance while it is being configured. A DbContext instance cannot be used inside 'OnConfiguring' since it is still being configured at this point. This can happen if a second operation is started on this context instance before a previous operation completed. Any instance members are not guaranteed to be thread safe.|ExceptionStack=   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at UrlShortener.Data.Repositories.Implementation.RepositoryBase`1.FindByConditon(Expression`1 expression, Boolean AsNoTracking) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\RepositoryBase.cs:line 17
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:18:52.9580|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.|ExceptionStack=   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:19:20.8997|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=An attempt was made to use the context instance while it is being configured. A DbContext instance cannot be used inside 'OnConfiguring' since it is still being configured at this point. This can happen if a second operation is started on this context instance before a previous operation completed. Any instance members are not guaranteed to be thread safe.|ExceptionStack=   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at UrlShortener.Data.Repositories.Implementation.RepositoryBase`1.FindByConditon(Expression`1 expression, Boolean AsNoTracking) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\RepositoryBase.cs:line 17
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:19:21.2243|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.|ExceptionStack=   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:19:46.2423|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=An attempt was made to use the context instance while it is being configured. A DbContext instance cannot be used inside 'OnConfiguring' since it is still being configured at this point. This can happen if a second operation is started on this context instance before a previous operation completed. Any instance members are not guaranteed to be thread safe.|ExceptionStack=   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at UrlShortener.Data.Repositories.Implementation.RepositoryBase`1.FindByConditon(Expression`1 expression, Boolean AsNoTracking) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\RepositoryBase.cs:line 17
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:21:11.7230|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=An attempt was made to use the context instance while it is being configured. A DbContext instance cannot be used inside 'OnConfiguring' since it is still being configured at this point. This can happen if a second operation is started on this context instance before a previous operation completed. Any instance members are not guaranteed to be thread safe.|ExceptionStack=   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at UrlShortener.Data.Repositories.Implementation.RepositoryBase`1.FindByConditon(Expression`1 expression, Boolean AsNoTracking) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\RepositoryBase.cs:line 17
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:21:14.9704|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=An attempt was made to use the context instance while it is being configured. A DbContext instance cannot be used inside 'OnConfiguring' since it is still being configured at this point. This can happen if a second operation is started on this context instance before a previous operation completed. Any instance members are not guaranteed to be thread safe.|ExceptionStack=   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at UrlShortener.Data.Repositories.Implementation.RepositoryBase`1.FindByConditon(Expression`1 expression, Boolean AsNoTracking) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\RepositoryBase.cs:line 17
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:22:16.5147|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=An attempt was made to use the context instance while it is being configured. A DbContext instance cannot be used inside 'OnConfiguring' since it is still being configured at this point. This can happen if a second operation is started on this context instance before a previous operation completed. Any instance members are not guaranteed to be thread safe.|ExceptionStack=   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at UrlShortener.Data.Repositories.Implementation.RepositoryBase`1.FindByConditon(Expression`1 expression, Boolean AsNoTracking) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\RepositoryBase.cs:line 17
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:22:58.6662|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=An attempt was made to use the context instance while it is being configured. A DbContext instance cannot be used inside 'OnConfiguring' since it is still being configured at this point. This can happen if a second operation is started on this context instance before a previous operation completed. Any instance members are not guaranteed to be thread safe.|ExceptionStack=   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at UrlShortener.Data.Repositories.Implementation.RepositoryBase`1.FindByConditon(Expression`1 expression, Boolean AsNoTracking) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\RepositoryBase.cs:line 17
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:23:38.2432|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=An attempt was made to use the context instance while it is being configured. A DbContext instance cannot be used inside 'OnConfiguring' since it is still being configured at this point. This can happen if a second operation is started on this context instance before a previous operation completed. Any instance members are not guaranteed to be thread safe.|ExceptionStack=   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at UrlShortener.Data.Repositories.Implementation.RepositoryBase`1.FindByConditon(Expression`1 expression, Boolean AsNoTracking) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\RepositoryBase.cs:line 17
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:23:38.4680|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.|ExceptionStack=   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:24:12.8032|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=An attempt was made to use the context instance while it is being configured. A DbContext instance cannot be used inside 'OnConfiguring' since it is still being configured at this point. This can happen if a second operation is started on this context instance before a previous operation completed. Any instance members are not guaranteed to be thread safe.|ExceptionStack=   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at UrlShortener.Data.Repositories.Implementation.RepositoryBase`1.FindByConditon(Expression`1 expression, Boolean AsNoTracking) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\RepositoryBase.cs:line 17
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:24:32.0740|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=An attempt was made to use the context instance while it is being configured. A DbContext instance cannot be used inside 'OnConfiguring' since it is still being configured at this point. This can happen if a second operation is started on this context instance before a previous operation completed. Any instance members are not guaranteed to be thread safe.|ExceptionStack=   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at UrlShortener.Data.Repositories.Implementation.RepositoryBase`1.FindByConditon(Expression`1 expression, Boolean AsNoTracking) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\RepositoryBase.cs:line 17
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:24:45.0014|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=An attempt was made to use the context instance while it is being configured. A DbContext instance cannot be used inside 'OnConfiguring' since it is still being configured at this point. This can happen if a second operation is started on this context instance before a previous operation completed. Any instance members are not guaranteed to be thread safe.|ExceptionStack=   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at UrlShortener.Data.Repositories.Implementation.RepositoryBase`1.FindByConditon(Expression`1 expression, Boolean AsNoTracking) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\RepositoryBase.cs:line 17
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:26:09.0401|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=An attempt was made to use the context instance while it is being configured. A DbContext instance cannot be used inside 'OnConfiguring' since it is still being configured at this point. This can happen if a second operation is started on this context instance before a previous operation completed. Any instance members are not guaranteed to be thread safe.|ExceptionStack=   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at UrlShortener.Data.Repositories.Implementation.RepositoryBase`1.FindByConditon(Expression`1 expression, Boolean AsNoTracking) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\RepositoryBase.cs:line 17
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:27:29.2327|WARN|PlanService.GetPlanAndCheckIfExists|Fetching plan '1' has failed by 10||ExceptionType=|ExceptionMessage=|ExceptionStack=
2025-09-17 09:29:25.6723|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=An attempt was made to use the context instance while it is being configured. A DbContext instance cannot be used inside 'OnConfiguring' since it is still being configured at this point. This can happen if a second operation is started on this context instance before a previous operation completed. Any instance members are not guaranteed to be thread safe.|ExceptionStack=   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at UrlShortener.Data.Repositories.Implementation.RepositoryBase`1.FindByConditon(Expression`1 expression, Boolean AsNoTracking) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\RepositoryBase.cs:line 17
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:29:25.8925|WARN|PlanService.GetPlanAndCheckIfExists|Fetching plan '1' has failed by 10||ExceptionType=|ExceptionMessage=|ExceptionStack=
2025-09-17 09:31:48.9435|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.|ExceptionStack=   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:31:49.0163|WARN|PlanService.GetPlanAndCheckIfExists|Fetching plan '1' has failed by 10||ExceptionType=|ExceptionMessage=|ExceptionStack=
2025-09-17 09:31:51.4995|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=An attempt was made to use the context instance while it is being configured. A DbContext instance cannot be used inside 'OnConfiguring' since it is still being configured at this point. This can happen if a second operation is started on this context instance before a previous operation completed. Any instance members are not guaranteed to be thread safe.|ExceptionStack=   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at UrlShortener.Data.Repositories.Implementation.RepositoryBase`1.FindByConditon(Expression`1 expression, Boolean AsNoTracking) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\RepositoryBase.cs:line 17
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:31:51.7235|WARN|PlanService.GetPlanAndCheckIfExists|Fetching plan '1' has failed by 10||ExceptionType=|ExceptionMessage=|ExceptionStack=
2025-09-17 09:31:58.9792|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=An attempt was made to use the context instance while it is being configured. A DbContext instance cannot be used inside 'OnConfiguring' since it is still being configured at this point. This can happen if a second operation is started on this context instance before a previous operation completed. Any instance members are not guaranteed to be thread safe.|ExceptionStack=   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at UrlShortener.Data.Repositories.Implementation.RepositoryBase`1.FindByConditon(Expression`1 expression, Boolean AsNoTracking) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\RepositoryBase.cs:line 17
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:31:59.1996|WARN|PlanService.GetPlanAndCheckIfExists|Fetching plan '1' has failed by 10||ExceptionType=|ExceptionMessage=|ExceptionStack=
2025-09-17 09:34:00.3112|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=An attempt was made to use the context instance while it is being configured. A DbContext instance cannot be used inside 'OnConfiguring' since it is still being configured at this point. This can happen if a second operation is started on this context instance before a previous operation completed. Any instance members are not guaranteed to be thread safe.|ExceptionStack=   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at UrlShortener.Data.Repositories.Implementation.RepositoryBase`1.FindByConditon(Expression`1 expression, Boolean AsNoTracking) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\RepositoryBase.cs:line 17
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:34:00.5343|WARN|PlanService.GetPlanAndCheckIfExists|Fetching plan '1' has failed by 10||ExceptionType=|ExceptionMessage=|ExceptionStack=
2025-09-17 09:34:31.9480|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.|ExceptionStack=   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:34:32.0222|WARN|PlanService.GetPlanAndCheckIfExists|Fetching plan '1' has failed by 10||ExceptionType=|ExceptionMessage=|ExceptionStack=
2025-09-17 09:45:40.7734|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.|ExceptionStack=   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.QueryingEnumerable`1.Enumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:45:40.8471|WARN|PlanService.GetPlanAndCheckIfExists|Fetching plan '1' has failed by 10||ExceptionType=|ExceptionMessage=|ExceptionStack=
2025-09-17 09:46:36.2838|WARN|PlanService.CreatePlanAsync|Creating plan has failed by 1||ExceptionType=System.InvalidOperationException|ExceptionMessage=An attempt was made to use the context instance while it is being configured. A DbContext instance cannot be used inside 'OnConfiguring' since it is still being configured at this point. This can happen if a second operation is started on this context instance before a previous operation completed. Any instance members are not guaranteed to be thread safe.|ExceptionStack=   at Microsoft.EntityFrameworkCore.DbContext.get_ContextServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.Set[TEntity]()
   at UrlShortener.Data.Repositories.Implementation.RepositoryBase`1.FindByConditon(Expression`1 expression, Boolean AsNoTracking) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\RepositoryBase.cs:line 17
   at UrlShortener.Data.Repositories.PlanRepository.ExistsAnyAsync(Expression`1 expression) in C:\Users\Shadow\source\repos\URLShortenerAPIDataAccessLayer\Repositories\Implementation\PlanRepository.cs:line 54
   at UrlShortener.Core.Services.Implementations.PlanService.hasNoConflict(Plan plan) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Services\Implementations\PlanService.cs:line 36
   at UrlShortener.Core.Domain.Results.ResultExtensions.EnsureAsync[U](Result`1 result, Func`2 predicate, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 167
   at UrlShortener.Core.Domain.Results.ResultExtensions.Tap[U](Task`1 task, Action`1 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 228
   at UrlShortener.Core.Domain.Results.ResultExtensions.TapAsync[U](Task`1 task, Func`2 action) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 231
   at UrlShortener.Core.Domain.Results.ResultExtensions.TryCatch[U](Task`1 task, Func`2 onFailure) in C:\Users\Shadow\source\repos\URLShortenerAPIBusinessLayer\Domain\Results\ResultExtensions.cs:line 276
2025-09-17 09:46:36.5056|WARN|PlanService.GetPlanAndCheckIfExists|Fetching plan '1' has failed by 10||ExceptionType=|ExceptionMessage=|ExceptionStack=
2025-09-17 12:48:15.6760|WARN|PlanService.GetPlanAndCheckIfExists|Fetching plan '99999' has failed by 10||ExceptionType=|ExceptionMessage=|ExceptionStack=
